version: 2.1

jobs:
  build-docs:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0d:4c:70:90:eb:cd:33:d2:51:d7:7b:9a:d9:8d:67:0e"
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            python -m docs.build
            git config user.email "workflow@circleci.com"
            git config user.name "CircleCI"
            git add docs
            git diff-index --quiet HEAD || git commit -m 'Automated README [ci skip]'
            git push origin master
          name: Building docs

workflows:
  main:
    jobs:
      - build-docs